name: Build and Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: Release to Github?
        required: false
        default: false
        type: boolean
      prerelease:
        description: Make it pre-release? This will also not set latest if true. But if triggered other in main branch, this is always true
        required: false
        default: true
        type: boolean
  push:
    branches:
      - main
    paths:
      - lib/**
      - assets/**
      - pubspec.yaml
      - pubspec.lock
      - android/**
      - ios/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  DART_DEFINE_ARGS: >
    API_SERVER_URL=${{ secrets.API_SERVER_URL }}
    SUPABASE_URL=${{ secrets.SUPABASE_URL }}
    SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
    OAUTH_GOOGLE_WEB_CLIENT_ID=${{ secrets.OAUTH_GOOGLE_WEB_CLIENT_ID }}
    OAUTH_GOOGLE_IOS_CLIENT_ID=${{ secrets.OAUTH_GOOGLE_IOS_CLIENT_ID }}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: Bump version
    if: ${{ inputs.release }}
    outputs:
      NEW_VERSION: ${{ steps.cz.outputs.version }}
      RELEASE_NOTE: ${{ steps.git-cliff.outputs.content }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.7.0

      - name: Get new version
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
          commit: false

      - name: Install version assist
        run: dart pub global activate version_assist

      - name: Update version and commit
        run: |
          version_assist set --version ${{ steps.cz.outputs.version }}
          version_assist commit

      - uses: fregante/setup-git-user@v2

      - name: Push back to repo
        run: |
          git add pubspec.yaml
          git push origin main --tags

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header

  build-apk:
    runs-on: ubuntu-latest
    name: Build APK
    if: success() || needs.bump-version.result == 'skipped'
    needs:
      - bump-version
    steps:
      - uses: actions/checkout@v4

      - uses: cedvdb/action-flutter-build-android@v1
        with:
          keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-password: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          build-cmd: flutter build apk --release ${{ env.DART_DEFINE_ARGS }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/*.apk

  build-ipa:
    runs-on: macos-latest
    name: Build IPA
    if: success() || needs.bump-version.result == 'skipped'
    needs:
      - bump-version
    steps:
      - uses: actions/checkout@v4

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --release --export-options-plist ios/Runner/Info.plist ${{ env.DART_DEFINE_ARGS }}
          certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: build/ios/ipa/*.ipa

  release:
    runs-on: ubuntu-latest
    name: Release
    needs:
      - build-apk
      - build-ipa
      - bump-version
    if: needs.bump-version.result == 'success'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        env:
          cool: true
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.bump-version.outputs.NEW_VERSION }}
          files: |
            build/app/outputs/flutter-apk/*.apk
            build/ios/ipa/*.ipa
          body: ${{ needs.bump-version.outputs.RELEASE_NOTE }}
          make_latest: ${{ ! inputs.prerelease && github.ref != 'main' }}
          prerelease: ${{ github.ref != 'main' || inputs.prerelease }}
