name: Commit Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize

env:
  FLUTTER_CHANNEL: stable

jobs:
  commitlint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'push' && 2 || 1 }}

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Get Dependencies
        run: flutter pub get

      - name: Validate Commits
        if: ${{ github.event_name == 'push' }}
        run: dart run commitlint_cli --from HEAD~1 --to HEAD

      - name: Validate Title of PR
        if: ${{ github.event_name == 'pull_request' }}
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE" | dart run commitlint_cli
