name: Dart Check

on:
  push:
    branches:
      - '**'
    paths:
      - '**.dart'

env:
  FLUTTER_VERSION: 3.29.x
  FLUTTER_CHANNEL: stable

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze
        run: dart analyze lib/

      - name: Format Check
        run: dart format --set-exit-if-changed lib/**.dart
