name: Dart Format Check

on:
  push:
    branches:
      - '**'

jobs:
  commitlint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable

      - name: Format Check
        run: dart format --set-exit-if-changed lib/**.dart
